#!/bin/sh
# Shim: translate Debian adduser flags to Wolfi/busybox adduser
# Common Debian patterns: adduser --disabled-password --gecos "" username
exec_args=""
username=""
skip_next=0
for arg in "$@"; do
    if [ "$skip_next" = "1" ]; then
        skip_next=0
        continue
    fi
    case "$arg" in
        --disabled-password|--disabled-login) ;;          # busybox default
        --gecos|--comment) skip_next=1 ;;                 # skip next arg
        --system) exec_args="$exec_args -S" ;;
        --no-create-home) exec_args="$exec_args -H" ;;
        --shell) exec_args="$exec_args -s" ;;
        --home) exec_args="$exec_args -h" ;;
        --uid) exec_args="$exec_args -u" ;;
        --ingroup|--gid) exec_args="$exec_args -G" ;;
        -*) ;;  # ignore unknown flags
        *) username="$arg" ;;
    esac
done
exec /usr/sbin/adduser $exec_args "$username"
