#!/bin/sh
# verify-sources.sh — verify every pinned source tarball against sources.json.
#
# This VERIFIES. It downloads each tarball, computes its SHA256, compares it
# against the pin in sources.json, and exits non-zero on any mismatch.
#
# The previous version did not verify anything. It downloaded each tarball,
# PRINTED the hash, and told you to paste it in ("Done. Paste SHA256 values into
# sources.json and Dockerfile.bootstrap ARG defaults."). It had nothing to
# compare against, so `make verify-sources` -- which the README advertises as the
# SHA256 check -- could not fail.
#
# Worse, it kept its OWN copy of every version number, and those had already
# drifted: it pinned apk-tools 2.14.4 while the build used 3.0.5, so it fetched
# and blessed the hash of a version that was never built. jemalloc was absent
# from it entirely, so its hash could not be regenerated by the documented
# workflow at all.
#
# sources.json is now the single source of truth. This also checks that the ARG
# defaults baked into the Dockerfiles still agree with it -- because those ARGs,
# not sources.json, are what actually gate the build.
#
# Usage:
#   scripts/verify-sources.sh               drift check + verify every hash
#   scripts/verify-sources.sh --drift-only  skip the downloads (fast; for CI)

set -eu

cd "$(dirname "$0")/.."

SOURCES="sources.json"
DOCKERFILES="dockerfiles/Dockerfile dockerfiles/Dockerfile.bootstrap"
DRIFT_ONLY=0
[ "${1:-}" = "--drift-only" ] && DRIFT_ONLY=1

command -v python3 >/dev/null 2>&1 || { echo "verify-sources: needs python3" >&2; exit 1; }
[ -f "$SOURCES" ] || { echo "verify-sources: $SOURCES not found" >&2; exit 1; }

fail=0

# ---------------------------------------------------------------------------
# 1. Drift: do the Dockerfile ARG defaults still match sources.json?
#
# The Dockerfiles carry their own copies of every version and hash, and those
# copies are what the build actually uses. sources.json is only a manifest. If
# they disagree, the manifest is a lie -- which is exactly what had happened.
# ---------------------------------------------------------------------------
echo "== Checking Dockerfile ARGs against $SOURCES =="

python3 - "$SOURCES" $DOCKERFILES <<'PY' || fail=1
import json, re, sys

sources_path = sys.argv[1]
dockerfiles  = sys.argv[2:]
src = json.load(open(sources_path))

# ARG names are not always derivable from the key.
ARG_NAME = {"apk-tools": "APK", "silex-nosync": None}

bad = 0
checked = 0
for name, meta in src.items():
    if name.startswith("_") or not isinstance(meta, dict):
        continue
    argbase = ARG_NAME.get(name, name.upper().replace("-", "_"))
    if argbase is None:
        continue

    want_v = meta.get("version")
    want_h = meta.get("sha256")

    for df in dockerfiles:
        text = open(df).read()
        m = re.search(r"^ARG %s_VERSION=(\S+)" % re.escape(argbase), text, re.M)
        if not m:
            continue                       # not built in this Dockerfile
        checked += 1
        if m.group(1) != want_v:
            print("  DRIFT  %-12s %s: ARG=%s, sources.json=%s"
                  % (name, df, m.group(1), want_v))
            bad += 1

        h = re.search(r"^ARG %s_SHA256=(\S+)" % re.escape(argbase), text, re.M)
        if h and want_h and h.group(1) != want_h:
            print("  DRIFT  %-12s %s: ARG sha256 differs from sources.json"
                  % (name, df))
            bad += 1

if bad:
    print("\n  %d drift(s). The Dockerfile ARGs gate the build; sources.json is"
          "\n  only a manifest. They must agree." % bad)
    sys.exit(1)
print("  OK: %d ARG pins match sources.json" % checked)
PY

if [ "$DRIFT_ONLY" -eq 1 ]; then
    if [ "$fail" -eq 0 ]; then
        echo "verify-sources: drift check passed"
    else
        echo "verify-sources: DRIFT DETECTED" >&2
    fi
    exit "$fail"
fi

# ---------------------------------------------------------------------------
# 2. Hashes: fetch each tarball and compare against its pin.
# ---------------------------------------------------------------------------
echo
echo "== Verifying tarball SHA256 against $SOURCES =="

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT INT TERM

python3 - "$SOURCES" > "$TMP/list" <<'PY'
import json, sys
src = json.load(open(sys.argv[1]))
for name, meta in src.items():
    if name.startswith("_") or not isinstance(meta, dict):
        continue
    if meta.get("sha256") in (None, "n/a"):
        continue
    if "url" in meta:
        print("%s\t%s\t%s" % (name, meta["sha256"], meta["url"]))
    else:
        # rust ships one tarball per arch
        for k in list(meta):
            if k.startswith("url_"):
                arch = k[4:]
                print("%s(%s)\t%s\t%s" % (name, arch, meta["sha256_" + arch], meta[k]))
PY

TAB=$(printf '\t')
while IFS="$TAB" read -r name want url; do
    [ -n "${name:-}" ] || continue
    printf '  %-20s ' "$name"
    if ! curl -fsSL --retry 3 --retry-delay 2 -o "$TMP/f" "$url" 2>/dev/null; then
        echo "FETCH FAILED  $url"
        fail=1
        continue
    fi
    got=$(sha256sum "$TMP/f" | awk '{print $1}')
    if [ "$got" = "$want" ]; then
        echo "ok"
    else
        echo "SHA256 MISMATCH"
        echo "      expected $want"
        echo "      got      $got"
        echo "      $url"
        fail=1
    fi
    rm -f "$TMP/f"
done < "$TMP/list"

echo
if [ "$fail" -ne 0 ]; then
    echo "verify-sources: FAILED" >&2
    exit 1
fi
echo "verify-sources: all sources verified against $SOURCES"
